[package]
name = "joubini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
color-eyre = "0.6.2"
log = "0.4"
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
nanoid = "0.4.0"
clap = { version = "4.4.13", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json"] }
actix-web = "4.4.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serial_test = "2.0.0"
