[package]
name = "joubini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
color-eyre = "0.6.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
nanoid = "0.4.0"
